// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rtcidlsswflnmguoqwfn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ0Y2lkbHNzd2Zsbm1ndW9xd2ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg1OTU1MzksImV4cCI6MjA2NDE3MTUzOX0.azf8u-A9s9vd6NaahP7OG_19TXrjDOs0ZZFA66FMDs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);